export enum ServicesAvailable {
  // Serviços de transferência
  PIX = 'PIX',
  TED = 'TED',
  DOC = 'DOC',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  INTERNATIONAL_TRANSFER = 'INTERNATIONAL_TRANSFER',

  // Serviços de pagamento
  BOLETO = 'BOLETO',
  CASH = 'CASH',
  CHECK = 'CHECK',

  // Serviços de crédito
  CREDIT_CARD = 'CREDIT_CARD',
  LOAN_PERSONAL = 'LOAN_PERSONAL',
  LOAN_CONSIGNED = 'LOAN_CONSIGNED',
  LOAN_PAYROLL = 'LOAN_PAYROLL',
  FINANCING = 'FINANCING',
  OVERDRAFT = 'OVERDRAFT',

  // Serviços de investimento
  SAVINGS = 'SAVINGS',
  INVESTMENT = 'INVESTMENT',
  FIXED_INCOME = 'FIXED_INCOME',
  VARIABLE_INCOME = 'VARIABLE_INCOME',

  // Serviços de seguro
  INSURANCE = 'INSURANCE',
  LIFE_INSURANCE = 'LIFE_INSURANCE',
  AUTO_INSURANCE = 'AUTO_INSURANCE',
  HOME_INSURANCE = 'HOME_INSURANCE',

  // Serviços de câmbio
  CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE',
  REMITTANCE = 'REMITTANCE',

  // Serviços administrativos
  ACCOUNT_MAINTENANCE = 'ACCOUNT_MAINTENANCE',
  CARD_MAINTENANCE = 'CARD_MAINTENANCE',
  STATEMENT = 'STATEMENT',

  // Serviços internos
  ADJUSTMENT = 'ADJUSTMENT',
  HOLD = 'HOLD',
  REVERSAL = 'REVERSAL',
  CHARGEBACK = 'CHARGEBACK',

  // Serviço padrão
  DEFAULT = 'DEFAULT',
}
