apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: default
data:
  kong.yml: |
    _format_version: "3.0"

    services:
      - name: orbe-ledger
        url: http://orbe-ledger-service:3000
        routes:
          - name: orbe-ledger-route
            paths:
              - /orbe-ledger
            strip_path: false
          - name: orbe-ledger-health-route
            paths:
              - /orbe-ledger/health
            strip_path: false

      - name: orbe-taxes
        url: http://orbe-taxes-service:3001
        routes:
          - name: orbe-taxes-route
            paths:
              - /orbe-taxes
            strip_path: false
          - name: orbe-taxes-health-route
            paths:
              - /orbe-taxes/health
            strip_path: false
