apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - postgres-init-configmap.yaml
  - postgres.yaml
  - configmap.yaml
  - secret.yaml
  - orbe-ledger.yaml
  - orbe-taxes.yaml
  - kong-configmap.yaml
  - kong.yaml

images:
  - name: orbe-ledger
    newName: orbe-ledger
    newTag: latest
  - name: orbe-taxes
    newName: orbe-taxes
    newTag: latest
