apiVersion: v1
kind: Secret
metadata:
  name: orbe-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "orbe-ledger"
  POSTGRES_USER: "orbe-ledger"
  POSTGRES_DB: "main-ledger"
  ORBE_LEDGER_DB_USER: "orbe-ledger"
  ORBE_LEDGER_DB_PASSWORD: "orbe-ledger"
  ORBE_LEDGER_DB_NAME: "main-ledger"
  ORBE_SERVICES_DB_USER: "orbe-services"
  ORBE_SERVICES_DB_PASSWORD: "orbe-services"
  ORBE_SERVICES_DB_NAME: "orbe-services"
