// src/common/enums/hold.enum.ts
export enum HoldStatus {
  ACTIVE = 'ACTIVE',
  CAPTURED = 'CAPTURED',
  RELEASED = 'RELEASED',
  EXPIRED = 'EXPIRED',
  PARTIALLY_CAPTURED = 'PARTIALLY_CAPTURED',
  CANCELLED = 'CANCELLED'
}


export enum HoldReason {
  CARD_AUTHORIZATION = 'CARD_AUTHORIZATION',
  ESCROW = 'ESCROW',
  DEPOSIT_GUARANTEE = 'DEPOSIT_GUARANTEE',
  SECURITY = 'SECURITY',
  DISPUTE = 'DISPUTE',
  FRAUD_PREVENTION = 'FRAUD_PREVENTION',
  PRE_AUTHORIZATION = 'PRE_AUTHORIZATION',
  RESERVATION = 'RESERVATION'
}