export enum JournalStatus {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum JournalType {
  TRANSFER = 'TRANSFER',
  PIX = 'PIX',
  TED = 'TED',
  DOC = 'DOC',
  FEE = 'FEE',
  SETTLEMENT = 'SETTLEMENT',
  REFUND = 'REFUND',
  REVERSAL = 'REVERSAL',
  HOLD = 'HOLD',
  RELEASE = 'RELEASE',
  CAPTURE = 'CAPTURE',
  ADJUSTMENT = 'ADJUSTMENT',
  CASHBACK = 'CASHBACK',
  TAX = 'TAX',
  INTEREST = 'INTEREST',
  TRANSFER_DEBIT = 'TRANSFER_DEBIT',
  LIQUIDACAO_SAIDA = 'LIQUIDACAO_SAIDA',
  LIQUIDACAO_ENTRADA = 'LIQUIDACAO_ENTRADA',
  TRANSFER_CREDIT = 'TRANSFER_CREDIT',
}

export enum EntrySide {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}
