export enum OutboxStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  RETRY = 'RETRY',
  DEAD = 'DEAD' // Dead letter - não vai mais tentar
}

export enum OutboxEventType {
  JOURNAL_CREATED = 'JOURNAL_CREATED',
  JOURNAL_POSTED = 'JOURNAL_POSTED',
  JOURNAL_REVERSED = 'JOURNAL_REVERSED',
  ENTRY_CREATED = 'ENTRY_CREATED',
  BALANCE_UPDATED = 'BALANCE_UPDATED',
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  HOLD_CREATED = 'HOLD_CREATED',
  HOLD_RELEASED = 'HOLD_RELEASED',
  RECONCILIATION_COMPLETED = 'RECONCILIATION_COMPLETED',
  HOLD_CAPTURED = 'HOLD_CAPTURED',
  HOLD_EXPIRED = 'HOLD_EXPIRED'
}