export enum ServicesAvailable {
  PIX = 'PIX',
  TED = 'TED',
  DOC = 'DOC',
  BOLETO = 'BOLETO',
  CASH = 'CASH',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  ADJUSTMENT = 'ADJUSTMENT',
  DEFAULT = 'DEFAULT'
}
