export enum TransactionStatus {
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
  CANCELLED = 'CANCELLED',
  PENDING_REVERSAL = 'PENDING_REVERSAL'
}

export enum TransactionType {
  TRANSFER = 'TRANSFER',
  PIX = 'PIX',
  TED = 'TED',
  DOC = 'DOC',
  BOLETO = 'BOLETO',
  CARD = 'CARD',
  INVESTMENT = 'INVESTMENT',
  FEE = 'FEE',
  REFUND = 'REFUND',
  REVERSAL = 'REVERSAL',
  ADJUSTMENT = 'ADJUSTMENT',
  CASHBACK = 'CASHBACK',
  SETTLEMENT = 'SETTLEMENT'
}